### ISSUE TITLE
There's a conflict in the naming of this project.

### ISSUE THREAD

**Issue by Dinoraptor101** [leviomagbemi/GenieAI#1]
I confused this with (ChatGPT - Genie AI) project.

the official repository for the popular Genie AI extension is: https://github.com/ai-genie/chatgpt-vscode
VS Code Extension link: https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode

Would you mind either renaming this repository or adding a redirection tip if someone is looking for the VS Code Extension so that they check the official link posted above? Thank you.

**Comment by leviomagbemi** [comment]
ok
